/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Whiskey,
} from './types/whiskey';

export namespace Components {
  interface AppRoot {}
  interface WhiskeyCard {
    'whiskey': Whiskey;
  }
  interface WhiskeyHome {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLWhiskeyCardElement extends Components.WhiskeyCard, HTMLStencilElement {}
  var HTMLWhiskeyCardElement: {
    prototype: HTMLWhiskeyCardElement;
    new (): HTMLWhiskeyCardElement;
  };

  interface HTMLWhiskeyHomeElement extends Components.WhiskeyHome, HTMLStencilElement {}
  var HTMLWhiskeyHomeElement: {
    prototype: HTMLWhiskeyHomeElement;
    new (): HTMLWhiskeyHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'whiskey-card': HTMLWhiskeyCardElement;
    'whiskey-home': HTMLWhiskeyHomeElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface WhiskeyCard extends JSXBase.HTMLAttributes<HTMLWhiskeyCardElement> {
    'whiskey'?: Whiskey;
  }
  interface WhiskeyHome extends JSXBase.HTMLAttributes<HTMLWhiskeyHomeElement> {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'whiskey-card': WhiskeyCard;
    'whiskey-home': WhiskeyHome;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


