/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Article,
} from './types/article';
import {
  Whiskey,
} from './types/whiskey';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppRoot {}
  interface WhiskeyArticle {
    'article': Article;
  }
  interface WhiskeyCard {
    'whiskey': Whiskey;
  }
  interface WhiskeyDetail {
    'match': MatchResults;
  }
  interface WhiskeyFilter {}
  interface WhiskeyHome {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLWhiskeyArticleElement extends Components.WhiskeyArticle, HTMLStencilElement {}
  var HTMLWhiskeyArticleElement: {
    prototype: HTMLWhiskeyArticleElement;
    new (): HTMLWhiskeyArticleElement;
  };

  interface HTMLWhiskeyCardElement extends Components.WhiskeyCard, HTMLStencilElement {}
  var HTMLWhiskeyCardElement: {
    prototype: HTMLWhiskeyCardElement;
    new (): HTMLWhiskeyCardElement;
  };

  interface HTMLWhiskeyDetailElement extends Components.WhiskeyDetail, HTMLStencilElement {}
  var HTMLWhiskeyDetailElement: {
    prototype: HTMLWhiskeyDetailElement;
    new (): HTMLWhiskeyDetailElement;
  };

  interface HTMLWhiskeyFilterElement extends Components.WhiskeyFilter, HTMLStencilElement {}
  var HTMLWhiskeyFilterElement: {
    prototype: HTMLWhiskeyFilterElement;
    new (): HTMLWhiskeyFilterElement;
  };

  interface HTMLWhiskeyHomeElement extends Components.WhiskeyHome, HTMLStencilElement {}
  var HTMLWhiskeyHomeElement: {
    prototype: HTMLWhiskeyHomeElement;
    new (): HTMLWhiskeyHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'whiskey-article': HTMLWhiskeyArticleElement;
    'whiskey-card': HTMLWhiskeyCardElement;
    'whiskey-detail': HTMLWhiskeyDetailElement;
    'whiskey-filter': HTMLWhiskeyFilterElement;
    'whiskey-home': HTMLWhiskeyHomeElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface WhiskeyArticle extends JSXBase.HTMLAttributes<HTMLWhiskeyArticleElement> {
    'article'?: Article;
  }
  interface WhiskeyCard extends JSXBase.HTMLAttributes<HTMLWhiskeyCardElement> {
    'whiskey'?: Whiskey;
  }
  interface WhiskeyDetail extends JSXBase.HTMLAttributes<HTMLWhiskeyDetailElement> {
    'match'?: MatchResults;
  }
  interface WhiskeyFilter extends JSXBase.HTMLAttributes<HTMLWhiskeyFilterElement> {
    'onWhiskeysFiltered'?: (event: CustomEvent<any>) => void;
  }
  interface WhiskeyHome extends JSXBase.HTMLAttributes<HTMLWhiskeyHomeElement> {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'whiskey-article': WhiskeyArticle;
    'whiskey-card': WhiskeyCard;
    'whiskey-detail': WhiskeyDetail;
    'whiskey-filter': WhiskeyFilter;
    'whiskey-home': WhiskeyHome;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


